title: OpenD6 Extension Project

collections_dir: docs

collections:
  attributes:
    output: true
    permalink: /:path
  professions:
    output: true
    permalink: /:path
  core_skills:
    output: true
    permalink: /:path
  genre_skills:
    output: true
    permalink: /:path
  systems:
    output: true
    permalink: /:path
  templates:
    output: true
    permalink: /:path

defaults:
  -
    scope:
      path: ''
    values:
      layout: 'default'
  -
    scope:
      path: ''
      type: 'attributes'
    values:
      layout: 'attribute'
  -
    scope:
      path: ''
      type: 'core_skills'
    values:
      layout: 'skill'
  -
    scope:
      path: ''
      type: 'genre_skills'
    values:
      layout: 'skill'
  -
    scope:
      path: ''
      type: 'professions'
    values:
      layout: 'profession'
