title: OpenD6 Project
description: Collecting and correlating data from the Open-D6 roleplaying game system.
github_username: ericabxy

theme: minima
minima:
  skin: dark
plugins:
  - jekyll-feed

collections_dir: docs

collections:
  attributes:
    output: true
    permalink: /:path
  professions:
    output: true
    permalink: /:path
  skills:
    output: true
    permalink: /:path
  systems:
    output: true
    permalink: /:path
  templates:
    output: true
    permalink: /:path

defaults:
  -
    scope:
      path: ''
    values:
      layout: 'default'
  -
    scope:
      path: ''
      type: 'attributes'
    values:
      layout: 'attribute'
  -
    scope:
      path: ''
      type: 'skills'
    values:
      layout: 'skill'
  -
    scope:
      path: ''
      type: 'professions'
    values:
      layout: 'profession'
